MIXED_CASE_WORDS = {
    "colorA",
    "DaVinci",
    "dLink",
    "EBook",
    "ePass", "eVar", "eRum", "eNeRGy",
    "fixIE",
    "fontS",
    "FromE",
    "GeoIP",
    "GitHub",
    "HowTo", "howTo",
    "InfluxDB",
    "iPad", "iPod",
    "isIE", "isIe", "isIOS", "isIos",
    "LaTeX",
    "lineY",
    "KOffice",
    "MattM",
    "McKim",
    "MySQL",
    "NokiaN",
    "OpenCV", "OpenUI", "OpenVz", "OpenZFS", "openXC",
    "pandaV",
    "payIn",
    "phpBB",
    "PICkit",
    "raiPlay",
    "ShowIE",
    "SQLite",
    "subId",
    "TikTok",
    "TimB",
    "typeOf",
    "UInt",
    "WebHelp",
    "WebKit",
    "WinNT",
    "wxPython",
    "YouTube",
}

GARBAGE_WORDS = {
    "al", "bp", "bt", "ev", "ne", "ti", "tn",

    "lou",

    "abaj", "abom", "aczk", "aian", "aifd", "aiii", "alav", "anei",
    "aocp", "apek", "arbi", "arla", "arzt", "avoj", "awae", "ayre",
    "bbbm", "bget", "bgnk", "bimf", "blfe", "bmfm", "bnml", "boxx",
    "brwd", "btac", "btau", "buyo", "bvgs", "cacs", "caoh", "cbap",
    "cbnz", "cedr", "cega", "cfms", "cfts", "chmi", "chwl", "cibl",
    "ckcq", "ckni", "cnte", "cocx", "coru", "cosb", "csum", "cync",
    "dcvg", "dlgn", "dlsw", "dmls", "drou", "dsbl", "dstp", "duhn",
    "dwyr", "ecrm", "eers", "efpn", "eili", "elfy", "enpq", "ephc",
    "eryk", "esic", "evli", "faus", "ffcv", "fffp", "fogm", "fols",
    "fosl", "fqpa", "fult", "gaso", "getv", "glim", "gwba", "gyom",
    "hafu", "haxe", "heva", "hisi", "hjas", "hmbs", "huta", "iesg",
    "ifcs", "iino", "imaj", "inap", "jark", "jdph", "jelq", "juhl",
    "jzee", "kaat", "kcmn", "kcpx", "kdim", "kdll", "kdma", "keol",
    "khor", "kica", "kjct", "kmro", "kqsw", "krlu", "ksgu", "ktyr",
    "kucb", "kvow", "kyvv", "kzce", "lcmc", "ldin", "lfmp", "lhaw",
    "ljuv", "lmmr", "lmna", "lotw", "lvdd", "mayr", "mdlp", "mimc",
    "miua", "mmja", "mrlv", "nafl", "nbpp", "ncvp", "ndlb", "nfsr",
    "ngii", "nidc", "nooh", "nsdf", "nzli", "obcs", "obdc", "ohbm",
    "ohwi", "onid", "ooad", "opot", "orgu", "oslo", "oust", "peil",
    "pfdc", "pfkw", "pflc", "pgpu", "piyi", "pmsa", "pnpt", "pori",
    "powi", "powm", "ptlh", "pwst", "pyqt", "pzfa", "qand", "qwsp",
    "raun", "rcgt", "rger", "righ", "ronc", "rrek", "rsra", "rugh",
    "rydz", "sagy", "sbsr", "scci", "secu", "secv", "seey", "seps",
    "sicl", "siom", "smek", "sncm", "sonk", "sufy", "sysk", "taqi",
    "tetr", "tfto", "tmbg", "tout", "tyra", "tyrs", "udre", "umrc",
    "urhg", "usaf", "usev", "usoy", "utel", "uvea", "uwtv", "vppa",
    "wakz", "wbof", "wbrc", "wdlb", "wehg", "whbg", "wmgw", "wmwd",
    "wnde", "wnng", "wnye", "wola", "wpht", "wrpu", "wtmi", "wtos",
    "wvgm", "wwoz", "wzxb", "wzxl", "xepm", "xgcd", "xhbs", "xyla",
    "ydih", "yeho", "yins", "yleg", "yoro", "zbxt", "zeju", "zelf",
    "zfyv", "zgfm", "zlea", "zwof",

    "baje", "bcbg", "cfar", "cfcs", "cfrd", "chex", "diem", "engs",
    "ervk", "guwz", "gykh", "hpha", "kaal", "kbbr", "kjsa", "klpt",
    "kmop", "lsnl", "neku", "nolu", "npma", "pefc", "pfoh", "plpa",
    "pssm", "pthr", "rfkc", "riyt", "sfwp", "shbu", "shcc", "swif",
    "ttpu", "uxii", "waxz", "wvrd", "yeba",

    "acpm", "ailp", "anvl", "apib", "asbj", "awin", "ayri", "azco",
    "bcix", "bgap", "bpop", "brbr", "calo", "cboe", "cgma", "ciro",
    "ciso", "cmmi", "crup", "cske", "cssv", "cuny", "cyng", "dcid",
    "ddps", "dtls", "dwin", "dzmb", "easi", "edar", "eend", "eita",
    "elso", "enhn", "epby", "esly", "exiv", "expm", "ezdk", "ffta",
    "fpjs", "fspl", "furu", "fwuu", "fyrd", "fyve", "gasv", "zuio",
    "gaub", "gehe", "genk", "glac", "gmap", "gruz", "gtin", "hier",
    "hino", "hjta", "hoog", "hsps", "huac", "igae", "jian", "kawn",
    "kdcj", "keif", "keni", "kisl", "kjhm", "kmez", "kodj", "kons",
    "koth", "kpmr", "kqfn", "ksaz", "ksho", "kwpv", "lere", "zcta",
    "libb", "libi", "llbn", "lloc", "lmaa", "loxo", "lscb", "mana",
    "marb", "marr", "mbek", "mmrv", "mmst", "mors", "moto", "mpdc",
    "mpsv", "mstr", "mvcc", "myhr", "navv", "ncdu", "nfsv", "nhay",
    "njak", "nsdd", "nsmb", "nuoc", "ocra", "oert", "okoc", "oliv",
    "omer", "ondo", "onli", "opus", "orla", "ostj", "ostm", "ownd",
    "padl", "padt", "pdtb", "plni", "poks", "psns", "psyc", "puci",
    "puxi", "qags", "raim", "rcmp", "reep", "resi", "riny", "ripv",
    "sacm", "schn", "sgkp", "slac", "smtv", "spai", "spsv", "yyys",
    "ssif", "stap", "swal", "swfu", "tchs", "temo", "thrd", "trff",
    "ttig", "uchc", "ujin", "valj", "wdnc", "wdpb", "ymfc", "ymry",
    "wfmo", "whjb", "widy", "wihm", "wlbr", "wlcb", "wllq", "wmob",
    "wnac", "wodr", "wqjj", "wran", "wsbl", "wtgz", "wufn", "wvov",
    "wwfe", "wwmy",

    "crysp", "datko", "eduke", "gehaz", "gukje", "gustu", "illam",
    "norrl", "ognia", "ozker", "rahum", "soffa", "ujman", "ulupo",
    "yogav",

    "ebis", "aure", "pas", "blico", "bcanka", "fianc", "lim",
}
